name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    - name: Build Application JAR
      working-directory: ./clinic-physiotherapys-clinic
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./clinic-physiotherapys-clinic
      run: docker-compose build

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:latest ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:latest 
      

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
