name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven


    - name: Build Backend JAR
      working-directory: ./physiotherapy-s-clinic
      run: mvn clean package

    - name: Docker Compose Build
      working-directory: ./physiotherapy-s-clinic
      run: docker-compose build
      
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:latest ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:latest
    
    - name: Build Frontend
      working-directory: ./fhysiotherapy-app
      run: |
        npm install
        npm run build
