name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Login no Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Configura JDK para o backend
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven

    # Compilar e construir o backend (Java/Spring Boot)
    - name: Build Backend JAR
      working-directory: ./physiotherapy.s.clinic  # Caminho onde está o backend (pom.xml)
      run: mvn clean package

    # Construir e gerar a imagem Docker usando docker-compose (para todo o projeto)
    - name: Docker Compose Build
      run: docker-compose build

    # Publicar no Docker Hub
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:latest ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/physiotherapy-s-clinic:latest

    # Build do Frontend (React) - FHysiotherapy App
    - name: Build Frontend
      working-directory: ./fhysiotherapy-app  # Caminho onde está o frontend (package.json)
      run: |
        npm install
        npm run build
