name: Continuous Integration With Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven

      - name: Build Backend JAR
        run: |
          cd clinic
          mvn clean package

      - name: Docker Compose Build
        run: |
          cd clinic
          docker-compose build

      - name: Push to Docker Hub Container Registry
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:latest ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:${{ github.run_id }}
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic-physiotherapys-clinic:latest

      - name: Build Frontend
        run: |
          cd frontend/fhysiotherapy-app
          npm install
          npm run build
